name: beautilly
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  another_flushbar: ^1.12.30
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.3
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  device_preview: ^1.2.0
  equatable: ^2.0.7
  firebase_core: ^3.12.1
  firebase_database: ^11.3.4
  firebase_messaging: ^15.2.4
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_colorpicker: ^1.0.3
  flutter_dotenv: ^5.2.1
  flutter_image_compress: ^2.1.0
  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter
  flutter_phoenix: ^1.1.1
  flutter_rating_bar: ^4.0.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.16
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  get_it: ^8.0.3
  google_maps_flutter: ^2.5.0
  http: ^1.2.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  modal_progress_hud_nsn: ^0.5.1
  path: ^1.8.3
  path_provider: ^2.1.2
  photo_view: ^0.15.0
  pin_code_fields: ^8.0.1
  shared_preferences: ^2.3.5
  shimmer: ^3.0.0
  url_launcher: ^6.2.5
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - assets/icons/
    - assets/map_style_light.json
    - assets/map_style_dark.json
    - .env
    
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
flutter_intl:
  enabled: true
