// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClBVUapIn5SKad5VWdyf2YoDnRfzh6r5g',
    appId: '1:836161149541:web:5e36367f2b28228409848c',
    messagingSenderId: '836161149541',
    projectId: 'dallik',
    authDomain: 'dallik.firebaseapp.com',
    databaseURL: 'https://dallik-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dallik.firebasestorage.app',
    measurementId: 'G-03M6F50QXL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEt_G22XCx2ysmQkMoUfMuzVZqhaPZzk0',
    appId: '1:836161149541:android:d23b9dd1df15c6c009848c',
    messagingSenderId: '836161149541',
    projectId: 'dallik',
    databaseURL: 'https://dallik-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dallik.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNkq33-7NJ06G3F5JsW-c73w-Hv1kcTHs',
    appId: '1:836161149541:ios:0b53be344cb75f2509848c',
    messagingSenderId: '836161149541',
    projectId: 'dallik',
    databaseURL: 'https://dallik-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dallik.firebasestorage.app',
    iosBundleId: 'com.example.beautilly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNkq33-7NJ06G3F5JsW-c73w-Hv1kcTHs',
    appId: '1:836161149541:ios:0b53be344cb75f2509848c',
    messagingSenderId: '836161149541',
    projectId: 'dallik',
    databaseURL: 'https://dallik-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dallik.firebasestorage.app',
    iosBundleId: 'com.example.beautilly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClBVUapIn5SKad5VWdyf2YoDnRfzh6r5g',
    appId: '1:836161149541:web:0472b89d5704399c09848c',
    messagingSenderId: '836161149541',
    projectId: 'dallik',
    authDomain: 'dallik.firebaseapp.com',
    databaseURL: 'https://dallik-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dallik.firebasestorage.app',
    measurementId: 'G-7QXX1637NH',
  );

}